name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  Validate_PR_Title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        if: github.event_name == 'pull_request'
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          echo "PR title: ${pr_title}"
          
          # Define the regex pattern for the PR title
          PR_TITLE_PATTERN="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\((account|inventory|general ledger)\): (.+) \[([A-Z]+-[0-9]+)\]$"
          
          if [[ ! "${pr_title}" =~ ${PR_TITLE_PATTERN} ]]; then
            echo "error: invalid PR title format"
            echo "Regex pattern: ${PR_TITLE_PATTERN}"
            
            # Print captured parts for debugging
            echo "Captured parts:"
            for i in {1..4}; do
              echo "   Group $i: ${BASH_REMATCH[$i]}"
            done
            
            exit 1
          fi

          echo "PR title validation successful"
