name: Validate PR Title on abs-sprint Branches

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  Validate_PR_Title:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          branch_name="${{ github.event.pull_request.head.ref }}"
          if [[ ! ${branch_name} =~ ^erp-sprint ]]; then
            echo "Skipping PR title validation as the branch does not start with 'erp-sprint'"
            exit 0
          fi

      - name: Check PR title
        if: startsWith(github.event.pull_request.head.ref, 'erp-sprint') && github.event_name == 'pull_request'
        run: |
          SKIP_LABEL="autorelease: pending"
          pr_labels='${{ toJSON(github.event.pull_request.labels) }}'

          if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
            echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
            exit 0
          fi

          pr_title="${{ github.event.pull_request.title }}"
          PR_NAME_RE="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\((Account|Configuration|Database|Finance|Inventory|Procurement|Sales|UI)\)(!)?: ([A-Z].*) \[O30-[0-9]+\]$"
          if [[ ! ${pr_title} =~ ${PR_NAME_RE} ]]; then
            echo "error: invalid PR title"
            echo "Example: feat: subject [OCH-1234]"
            exit 1
          fi
